# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
