# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_person_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='about_me',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_page',
            field=models.URLField(null=True),
        ),
    ]
