# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170906_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='users/img'),
        ),
    ]
