# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to=settings.AUTH_USER_MODEL),
        ),
    ]
