# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
