# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 12:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import learning_logs.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0011_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(learning_logs.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
