# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_auto_20170920_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
