# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0012_auto_20170913_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('default', 'Gray'), ('primary', 'Blue'), ('success', 'Green'), ('info', 'Cyan'), ('warning', 'Yellow'), ('danger', 'Red')], default='default', max_length=10)),
                ('title', models.CharField(blank=True, max_length=30, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='tag',
            field=models.ManyToManyField(blank=True, default='', to='learning_logs.Tag'),
        ),
    ]
