# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0013_auto_20170921_0418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['title'], 'verbose_name_plural': 'entries'},
        ),
    ]
