# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0014_auto_20170918_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True, unique=True),
            preserve_default=False,
        ),
    ]
