# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0016_loglikedentries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogViewedEntries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(max_length=20)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.Entry')),
            ],
        ),
    ]
