# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
